name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {
              "features": [
                {"create": {"domain": "app-salon-php-mvc-jaime.mnz.dom.my.id", "user": "app-salon-php-mvc-jaime", "pass": "<redacted>", "email": "vargasarenasjosejaime@gmail.com"}},
                "firewall",
                "php 8.3",
                "mysql",
                "ssl",
                "ssl always"
              ],
              "source": "https://github.com/Jaime829/appsalon-php-mvc",
              "root": "public_html/public",
              "nginx": {
                "fastcgi": "on",
                "locations": [
                  {
                    "match": "/",
                    "try_files": "$uri $uri/ /index.php$is_args$args"
                  },
                  {
                    "match": "~ \\.php$",
                    "fastcgi": "on"
                  }
                ]
              },
              "commands": [
                "echo \"display_errors = On\" > .user.ini",
                "echo \"display_startup_errors = On\" >> .user.ini",
                "mkdir -p includes",
                "echo \"DB_HOST=localhost\" > includes/.env",
                "echo \"DB_USER=${USERNAME}\" >> includes/.env",
                "echo \"DB_PASS=${PASSWORD}\" >> includes/.env",
                "echo \"DB_NAME=${DATABASE}\" >> includes/.env",
                "echo \"\" >> includes/.env",
                "echo \"EMAIL_HOST=${{ secrets.EMAIL_HOST }}\" >> includes/.env",
                "echo \"EMAIL_USER=${{ secrets.EMAIL_USER }}\" >> includes/.env",
                "echo \"EMAIL_PASS=${{ secrets.EMAIL_PASS }}\" >> includes/.env",
                "echo \"EMAIL_PORT=${{ secrets.EMAIL_PORT }}\" >> includes/.env",
                "echo \"EMAIL_FROM=${{ secrets.EMAIL_FROM }}\" >> includes/.env",
                "echo \"\" >> includes/.env",
                "echo \"APP_URL=https://${DOMAIN}\" >> includes/.env",
                "composer install --no-dev"
              ]
            }